# Feed options
host: "https://username:password@localhost/feed"

# SSL options
verify_peer: true
verify_host: true

#  ssl_version available: 3-> SSLv3,  2 -> SSLv2 
ssl_version: 2

# Daemon options
check_interval: 10 # in seconds

# Nortification url
notify_url: "http://localhost:3000/notify"
